version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    networks:
      - backend
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    networks:
      - backend
    depends_on:
      - database
      - storage
    ports:
      - '8000:8000'
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - backend
  storage:
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DEFAULT_BUCKETS: mybucket
      MINIO_SERVER_ACCESS_KEY: minioaccess
      MINIO_SERVER_SECRET_KEY: miniosecret
    volumes:
      - ./storage:/bitnami/minio/data
    networks:
      - backend
    ports:
      - '9001:9001'
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - '80:80'
    networks:
      - backend
    depends_on:
      - backend
      - storage
      - database
networks:
  backend:
    driver: bridge
volumes:
  database: